spring:
  application:
    name: tural-final-project
  datasource:
    url: jdbc:postgresql://localhost:5432/final_project
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    access:
      secret: q9Xf2KzL7mVtP4rYc8NwE1aSdG6hJkR3uB5yTzU0iOx=
      expiration: 900000
    refresh:
      expiration: 86400000